name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  UPSTREAM_REPO: https://github.com/FloatTech/ZeroBot-Plugin.git
  UPSTREAM_BRANCH: master
  TARGET_BRANCH: DisableOnDefault
  BACKUP_FILES: './scripts/DisableOnDefault.sh .github/workflows/DisableOnDefault.yml'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add upstream remote
      run: |
        git remote add upstream ${{ env.UPSTREAM_REPO }}
        git fetch upstream

    - name: Backup files
      run: |
        for file in ${{ env.BACKUP_FILES }}; do
          if [ -e "$file" ]; then
            mv "$file" "$file.bak"
          fi
        done

    - name: Reset to upstream
      run: |
        git checkout -B ${{ env.TARGET_BRANCH }}
        git reset --hard upstream/${{ env.UPSTREAM_BRANCH }}

    - name: Restore files
      run: |
        for file in ${{ env.BACKUP_FILES }}; do
          if [ -e "$file.bak" ]; then
            rm -rf "$file"
            mv "$file.bak" "$file"
          fi
        done

    - name: Apply Custon Patches
      run: |
        chmod +x ./scripts/DisableOnDefault.sh
        bash ./scripts/DisableOnDefault.sh
        for file in ${{ env.BACKUP_FILES }}; do
          if [ -e "$file" ]; then
            git add "$file"
          fi
        done
        git add .

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Sync with upstream + custom changes" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
